### ISSUE TITLE
Sporadic Server Crash on Forge 2766

### ISSUE THREAD

**Issue by SalmonSays** [TheCBProject/WirelessRedstone#14]
Using "WR-CBE-1.12.2-2.3.1.30-universal" against "forge-1.12.2-14.23.5.2766-universal" has resulted in the following NullPointerException stemming seemingly from WR-CBE on a modded server instance:

https://hastebin.com/oyopaxejuv.http

It's not a regular crash that I can easily reproduce, but I have two practically identical crash reports from a few hours apart. If there's any other info I can provide, let me know!

**Comment by LotuxPunk** [comment]
Same on 2768  https://pastebin.com/2i9JuMr7

**Comment by Magei** [comment]
Me also on 2768

 wrcbe | 2.3.1 | WR-CBE-1.12.2-2.3.1.30-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |

[crash-2018-12-11_06.30.24-server.txt](https://github.com/TheCBProject/WirelessRedstone/files/2666143/crash-2018-12-11_06.30.24-server.txt)

**Comment by VADemon** [comment]
Bump.

```
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at codechicken.wirelessredstone.manager.RedstoneEtherServer.updateJammedNodes(RedstoneEtherServer.java:552)
	at codechicken.wirelessredstone.manager.RedstoneEtherServer.tick(RedstoneEtherServer.java:533)
	at codechicken.wirelessredstone.handler.WREventHandler.serverTick(WREventHandler.java:160)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_855_WREventHandler_serverTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:274)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:776)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by covers1624** [comment]
I've done what i can for this, added some null checks.

**Comment by Charismara** [comment]
same on 2836 https://pastebin.com/DLQGGxaS
